# Usar a imagem base do Node.js
FROM node:14

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar os arquivos da aplicação para dentro do container
COPY . .

# Instalar as dependências
RUN npm install

# Expor a porta que o serviço vai usar
EXPOSE 3000

# Comando para rodar a aplicação
CMD ["node", "app.js"]
