version: "3.8"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=auth_db

  payment-service:
    build: ./payment-service
    ports:
      - "3001:3000"
    networks:
      - backend
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=payment_db

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
